export enum MessageCodes {
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",
  VALIDATION_ERROR = "VALIDATION_ERROR",

  MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",

  MISSING_SECURITY_KEY = "MISSING_SECURITY_KEY",

  REQUIRED_FIELD = "REQUIRED_FIELD",

  INVALID_EMAIL = "INVALID_EMAIL",

  INVALID_PASSWORD = "INVALID_PASSWORD",

  EXISTING_USER = "EXISTING_USER",

  AUTH_FAILED = "AUTH_FAILED",

  SERVER_ERROR = "SERVER_ERROR",

  NOT_FOUND = "NOT_FOUND",

  UNAUTHORIZED = "UNAUTHORIZED",

  API_ERROR = "API_ERROR",
}

export enum ErrorCodes {
  ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND",

  API_ERROR = "API_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  EXISTING_USER_FOUND = "EXISTING_USER_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  PASSWORD_NOT_MATCHING = "PASSWORD_NOT_MATCHING",
  INVALID_CONFIGURATION = "INVALID_CONFIGURATION",

  /// Registration related
  REGISTRATION_FAILED = "REGISTRATION_FAILED",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

  /// Login related
  USER_MISSING_PASSWORD = "USER_MISSING_PASSWORD",

  /// JWT related
  MISSING_JWT_SECRET = "MISSING_JWT_SECRET",
  JWT_SECRET_TOO_SHORT = "JWT_SECRET_TOO_SHORT",

  /// Email related
  MISSING_EMAIL = "MISSING_EMAIL",
  INVALID_EMAIL = "INVALID_EMAIL",

  USERNAME_TOO_SHORT = "USERNAME_TOO_SHORT",
  USERNAME_TOO_LONG = "USERNAME_TOO_LONG",
  MISSING_USERNAME = "MISSING_USERNAME",

  /// Password related
  MISSING_PASSWORD = "MISSING_PASSWORD",
  MISSING_PASSWORD_CONFIRMATION = "MISSING_PASSWORD_CONFIRMATION",
  PASSWORD_TOO_SHORT = "PASSWORD_TOO_SHORT",
  PASSWORD_TOO_LONG = "PASSWORD_TOO_LONG",
  PASSWORD_MISSING_UPPERCASE = "PASSWORD_MISSING_UPPERCASE",
  PASSWORD_MISSING_LOWERCASE = "PASSWORD_MISSING_LOWERCASE",
  PASSWORD_MISSING_NUMBER = "PASSWORD_MISSING_NUMBER",
  PASSWORD_MISSING_SPECIAL_CHAR = "PASSWORD_MISSING_SPECIAL_CHAR",

  MISSING_SECURITY_KEY = "MISSING_SECURITY_KEY",
  SECURITY_KEY_TOO_SHORT = "SECURITY_KEY_TOO_SHORT",
  MISSING_COOKIE_EXPIRATION = "MISSING_COOKIE_EXPIRATION",

  MISSING_COOKIE_NAME = "MISSING_COOKIE_NAME",
  MISSING_TOKEN = "MISSING_TOKEN",
  MISSING_HASH = "MISSING_HASH",
  MISSING_USER_ID = "MISSING_USER_ID",

  VERIFICATION_CODE_NOT_FOUND = "VERIFICATION_CODE_NOT_FOUND",
  VERIFICATION_CODE_EXPIRED = "VERIFICATION_CODE_EXPIRED",

  USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED",
}
