import {
  loginPre1,
  loginPre2,
  registerPre1,
  registerPre2,
  mePre1,
  mePre2,
  logoutPre1,
  logoutPre2,
  changePasswordPre1,
  changePasswordPre2,
  refreshTokenPre1,
  refreshTokenPre2,
  statusPre1,
  statusPre2,
  requestPasswordChangePre1,
  requestPasswordChangePre2,
  validatePasswordRequestCodePre1,
  validatePasswordRequestCodePre2,
} from "./auth.pre.middleware";

import {
  meProfilePre1,
  meProfilePre2,
  updateEmailPre1,
  updateEmailPre2,
  updateUsernamePre1,
  updateUsernamePre2,
  deactivateAccountPre1,
  deactivateAccountPre2,
  reactivateAccountPre1,
  reactivateAccountPre2,
  singleUserPre1,
  singleUserPre2,
  deleteAccountPre1,
  deleteAccountPre2,
  publicProfilePre1,
  publicProfilePre2,
} from "./me.pre.middleware";

import {
  getSessionsPre1,
  getSessionsPre2,
  postLogoutOthersPre1,
  postLogoutOthersPre2,
  postEnable2FAPre1,
  postEnable2FAPre2,
  postDisable2FAPre1,
  postDisable2FAPre2,
  postVerify2FAPre1,
  postVerify2FAPre2,
} from "./security.pre.middleware";

export {
  loginPre1,
  loginPre2,
  registerPre1,
  registerPre2,
  mePre1,
  mePre2,
  logoutPre1,
  logoutPre2,
  changePasswordPre1,
  changePasswordPre2,
  refreshTokenPre1,
  refreshTokenPre2,
  statusPre1,
  statusPre2,
  requestPasswordChangePre1,
  requestPasswordChangePre2,
  validatePasswordRequestCodePre1,
  validatePasswordRequestCodePre2,
  meProfilePre1,
  meProfilePre2,
  updateEmailPre1,
  updateEmailPre2,
  updateUsernamePre1,
  updateUsernamePre2,
  deactivateAccountPre1,
  deactivateAccountPre2,
  reactivateAccountPre1,
  reactivateAccountPre2,
  singleUserPre1,
  singleUserPre2,
  deleteAccountPre1,
  deleteAccountPre2,
  publicProfilePre1,
  publicProfilePre2,
  getSessionsPre1,
  getSessionsPre2,
  postLogoutOthersPre1,
  postLogoutOthersPre2,
  postEnable2FAPre1,
  postEnable2FAPre2,
  postDisable2FAPre1,
  postDisable2FAPre2,
  postVerify2FAPre1,
  postVerify2FAPre2,
};
